// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okfcdlwffhzcdfwjagop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZmNkbHdmZmh6Y2Rmd2phZ29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDIyNzcsImV4cCI6MjA2NzMxODI3N30.CDDvUqSKb6399eH59akGEbzJGVqfJvjcy__gcPblc5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});